### ISSUE TITLE
Add package: onnx

### ISSUE THREAD

**Issue by josephrocca** [pyodide/pyodide-recipes#216]
## 🐍 Package Request

- Package Name and Version : onnx / v1.13.0 (latest)
- Package URL : https://github.com/onnx/onnx/tree/v1.13.0
- Package Dependencies that needs to be resolved first: [protobuf](https://github.com/pyodide/pyodide/issues/3424)

# Build instructions
```bash
git clone --branch v21.12 https://github.com/onnx/onnx
cd onnx
git submodule update --init --recursive

# pyodide setup:
pip install pyodide-build

# install emscripten
git clone https://github.com/emscripten-core/emsdk
cd emsdk
pyodide config get emscripten_version  # this line is needed due to: https://github.com/pyodide/pyodide/issues/3430
PYODIDE_EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
./emsdk install ${PYODIDE_EMSCRIPTEN_VERSION}
./emsdk activate ${PYODIDE_EMSCRIPTEN_VERSION}
source emsdk_env.sh
cd ../

# install protobuf (not just binary)
git clone https://github.com/protocolbuffers/protobuf.git
cd protobuf
git checkout v3.20.2
git submodule update --init --recursive
mkdir build_source && cd build_source
cmake ../cmake -Dprotobuf_BUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_POSITION_INDEPENDENT_CODE=ON -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release
make -j$(nproc)
sudo make install
cd ../../

pip install "pybind11[global]"
export PATH="$(pwd)/protobuf/build_source:$PATH"
export CMAKE_ARGS="-DONNX_USE_LITE_PROTO=ON -DProtobuf_INCLUDE_DIR=$(pwd)/protobuf/src -DProtobuf_LIBRARIES=$(pwd)/protobuf/build_source -DProtobuf_LITE_LIBRARY=$(pwd)/protobuf/build_source/libprotobuf-lite.a -Dpybind11_DIR=$(python -c 'import pybind11 as _; print(_.__path__[0])')/share/cmake/pybind11 -DPYTHON_INCLUDE_DIR=$(python -c "import sysconfig; print(sysconfig.get_path('include'))") -DPYTHON_LIBRARY=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")"
pyodide build
```

# Progress so far

The above build instruction seem to work fine, but the next issue that I'm working through is this runtime error:

```
Failed to load dynlib /lib/python3.10/site-packages/onnx/onnx_cpp2py_export.cpython-310-wasm32-emscripten.so. We probably just tried to load a linux .so file or something.

Uncaught PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/_pyodide/_base.py", line 531, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 8, in <module>
  File "/lib/python3.10/site-packages/onnx/__init__.py", line 6, in <module>
    from .onnx_cpp2py_export import ONNX_ML  # noqa
ImportError: dynamic module does not define module export function (PyInit_onnx_cpp2py_export)
```

 * demo: https://josephrocca.github.io/onnx-pyodide/demo
 * repo: https://github.com/josephrocca/onnx-pyodide

I haven't actually looked into this too deeply (other than googling "pyodide dynlib", which didn't turn up anything immediately relevant-looking), and so I intent to keep pushing on this tomorrow, but if anyone has any tips on how to handle dynamic libs in Pyodide, please do share - I'm really just bumbling along here with not much idea what I'm doing ^^

I'll update this issue with my progress as I go.

**Comment by metalmancode** [comment]
I have a reproducible experimental ONNX 1.15.0 recipe working with Pyodide
0.29.4 / Python 3.13 (`pyodide-build` 0.34.4).

The port handles three cross-compilation points:

- it uses a host-native `protoc` while compiling the Protobuf runtime to Wasm;
- it supplies the target Python headers from Pyodide's cross-build
  environment; and
- it removes ONNX's ELF-only `--exclude-libs` linker option.

I also tested the complete browser path, not only `import onnx`:

1. train `sklearn.linear_model.LogisticRegression` in Pyodide;
2. convert it with `skl2onnx` 1.19.1;
3. validate and serialize with ONNX 1.15.0; and
4. execute the generated 379-byte model with ONNX Runtime Web 1.22.0.

The public recipe, patches, structural check, and browser proof are here:
https://github.com/metalmancode/onnx-pyodide

Live end-to-end proof:
https://metalmancode.github.io/onnx-pyodide/demo/

Release and wheel:
https://github.com/metalmancode/onnx-pyodide/releases/tag/v0.1.0

The locally reproduced wheel SHA-256 is:
`2a827f6e2649395743afac49186343ca9221f48a1c67cce300cd019a7f448cd4`

This work came from the browser-local ML pipeline used in MLDeck:
https://mldeck.com/

For related browser-ML integration or collaboration:
contact@mldeck.com

I would be happy to adapt the recipe to the repository's current conventions.
Would maintainers prefer a pull request with this proven ONNX 1.15 version set,
or an update to a newer ONNX release first?

**Comment by ryanking13** [comment]
Thanks to @andife, onnx is building and publishing Pyodide wheels to PyPI

**Comment by andife** [comment]
If anyone here has any interesting use cases for the package—whether now or in the future—that are publicly available, please let me know; I find that very interesting,

**Comment by metalmancode** [comment]
Thanks for asking about public use cases. I have a working browser-local use case built from this capability.

MLDeck uses ONNX graph construction and serialization inside Pyodide as part of a browser-local machine-learning workflow. I also published a minimal end-to-end proof that trains a scikit-learn model in the browser, converts it with skl2onnx, validates and serializes it with ONNX, and executes the generated model with ONNX Runtime Web.

Live proof: https://metalmancode.github.io/onnx-pyodide/demo/
Source and reproducibility notes: https://github.com/metalmancode/onnx-pyodide
Product use case: https://mldeck.com/

I am now looking into the current 2026 ABI gap mentioned above and will follow up in the ONNX repository with tested results.

— Gholamreza Rashidi Ardestani
contact@mldeck.com
